sudo: required
services:
  - docker
language: c
script:
  - ./.docker.sh
env:
  matrix:
  - DISTRO="debian-stable"
  - DISTRO="alpine"
  - DISTRO="ubuntu-16.04"
  - DISTRO="ubuntu"
  - OCAMLFORMAT="0.9"
