language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - PACKAGE="hex"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.02.3
   - DISTRO=debian-testing OCAML_VERSION=4.03.0
   - DISTRO=debian-unstable OCAML_VERSION=4.04.0
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.04.1
   - DISTRO=centos-7 OCAML_VERSION=4.03.0
   - DISTRO=alpine-3.5 OCAML_VERSION=4.04.1
   - DISTRO=alpine OCAML_VERSION=4.06.0
